name: test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.19.0'
      - name: install task
        run: curl -Ls https://git.io/ttask.sh | sh
      - name: run tests
        run: ./bin/task test
      - name: process coverage
        run: ./bin/task coverage
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
      - name: install task
        run: curl -Ls https://git.io/ttask.sh | sh
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
      - name: run linter
        run: ./bin/task lint
  release:
    name: Release 
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install changelogger
        run: curl -Ls https://git.io/changelogger.sh | sh
      - name: Save changelog entries of current release
        run: ./bin/changelogger release last > CHANGELOG_RELEASE.md
      - name: Print changelog entries for debugging
        run: cat CHANGELOG_RELEASE.md
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          body_path: CHANGELOG_RELEASE.md
          token: ${{ secrets.GITHUB_TOKEN }}
